In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

ROOT = Path.cwd().parent

DATA_DIR = ROOT / "data" / "raw" / "restaurants"

In [2]:
business = pd.read_json(
    DATA_DIR / "business.json",
    lines=True
)

review = pd.read_json(
    DATA_DIR / "review.json",
    lines=True
)

tip = pd.read_json(
    DATA_DIR / "tip.json",
    lines=True
)

In [3]:
print("Businesses :", len(business))
print("Reviews    :", len(review))
print("Tips       :", len(tip))

Businesses : 150346
Reviews    : 6990280
Tips       : 908915

In [4]:
print("Business columns")
print(business.columns.tolist())

print("\nReview columns")
print(review.columns.tolist())

print("\nTip columns")
print(tip.columns.tolist())

Business columns
['business_id', 'name', 'address', 'city', 'state', 'postal_code', 'latitude', 'longitude', 'stars', 'review_count', 'is_open', 'attributes', 'categories', 'hours']

Review columns
['review_id', 'user_id', 'business_id', 'stars', 'useful', 'funny', 'cool', 'text', 'date']

Tip columns
['user_id', 'business_id', 'text', 'date', 'compliment_count']

In [5]:
display(business.head())

display(review.head())

display(tip.head())

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15

,user_id,business_id,text,date,compliment_count
0,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0
2,-copOvldyKh1qr-vzkDEvw,MYoRNLb5chwjQe3c_k37Gg,It's open even when you think it isn't,2013-08-18 00:56:08,0
3,FjMQVZjSqY8syIO-53KFKw,hV-bABTK-glh5wj31ps_Jw,Very decent fried chicken,2017-06-27 23:05:38,0
4,ld0AperBXk1h6UbqmM80zw,_uN0OudeJ3Zl_tf6nxg5ww,Appetizers.. platter special for lunch,2012-10-06 19:43:09,0

In [6]:
business.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150346 entries, 0 to 150345
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   business_id   150346 non-null  object
 1   name          150346 non-null  object
 2   address       150346 non-null  object
 3   city          150346 non-null  object
 4   state         150346 non-null  object
 5   postal_code   150346 non-null  object
 6   latitude      150346 non-null  float64
 7   longitude     150346 non-null  float64
 8   stars         150346 non-null  float64
 9   review_count  150346 non-null  int64
 10  is_open       150346 non-null  int64
 11  attributes    136602 non-null  object
 12  categories    150243 non-null  object
 13  hours         127123 non-null  object
dtypes: float64(3), int64(2), object(9)
memory usage: 16.1+ MB

In [7]:
review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6990280 entries, 0 to 6990279
Data columns (total 9 columns):
 #   Column       Dtype
---  ------       -----
 0   review_id    object
 1   user_id      object
 2   business_id  object
 3   stars        int64
 4   useful       int64
 5   funny        int64
 6   cool         int64
 7   text         object
 8   date         datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 480.0+ MB

In [8]:
tip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 908915 entries, 0 to 908914
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   user_id           908915 non-null  object
 1   business_id       908915 non-null  object
 2   text              908915 non-null  object
 3   date              908915 non-null  datetime64[ns]
 4   compliment_count  908915 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 34.7+ MB

In [9]:
restaurants = business[
    business["categories"]
    .fillna("")
    .str.contains("Restaurants")
].copy()

print("Restaurants:", len(restaurants))

Restaurants: 52268

In [10]:
restaurants[
    [
        "business_id",
        "name",
        "stars",
        "review_count",
        "categories",
        "city",
        "state"
    ]
].head()

,business_id,name,stars,review_count,categories,city,state
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,4.0,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...",Philadelphia,PA
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,2.0,6,"Burgers, Fast Food, Sandwiches, Food, Ice Crea...",Ashland City,TN
8,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,3.0,19,"Pubs, Restaurants, Italian, Bars, American (Tr...",Affton,MO
9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,1.5,10,"Ice Cream & Frozen Yogurt, Fast Food, Burgers,...",Nashville,TN
11,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,4.0,10,"Vietnamese, Food, Restaurants, Food Trucks",Tampa Bay,FL

In [11]:
restaurants["stars"].describe()

count    52268.000000
mean         3.515172
std          0.829593
min          1.000000
25%          3.000000
50%          3.500000
75%          4.000000
max          5.000000
Name: stars, dtype: float64

In [12]:
restaurants["review_count"].describe()

count    52268.000000
mean        87.267142
std        188.939711
min          5.000000
25%         13.000000
50%         33.000000
75%         89.000000
max       7568.000000
Name: review_count, dtype: float64

In [13]:
restaurants[
    [
        "name",
        "review_count",
        "stars"
    ]
].sort_values(
    "review_count",
    ascending=False
).head(20)

                                      name  review_count  stars
113731                   Acme Oyster House          7568    4.0
112552                        Oceana Grill          7400    4.0
91757   Hattie B’s Hot Chicken - Nashville          6093    4.5
143157             Reading Terminal Market          5721    4.5
147081          Ruby Slipper - New Orleans          5193    4.5
100024                 Mother's Restaurant          5185    3.5
31033                          Royal House          5070    4.0
31332                   Commander's Palace          4876    4.5
4497                                  Luke          4554    4.0
97331                               Cochon          4421    4.0
113983                Pat's King of Steaks          4250    3.0
148829                 Biscuit Love: Gulch          4207    4.0
132673                  Pappy's Smokehouse          3999    4.5
64541      Felix's Restaurant & Oyster Bar          3966    4.0
42331                           Gumbo Shop          3902    4.0
49618                       Cochon Butcher          3837    4.5
129349                          Los Agaves          3834    4.5
73096            Willie Mae's Scotch House          3582    4.5
57332                        Geno's Steaks          3401    2.5
137449                                Datz          3260    4.0

In [14]:
restaurants["categories"].sample(10, random_state=42)

92932     Restaurants, Pizza, American (New), Bars, Burg...
81896     Street Vendors, Food Stands, Barbeque, Food, R...
60706                       Restaurants, Fast Food, Burgers
120250                  Restaurants, American (Traditional)
137438         Restaurants, Buffets, Soup, Chinese, Seafood
118209    Health & Medical, Dentists, Pizza, Italian, Or...
10557        Breakfast & Brunch, Restaurants, Mediterranean
91618                                    Restaurants, Pizza
79120     Music Venues, Bars, Nightlife, Arts & Entertai...
97805                 Restaurants, Pizza, Sandwiches, Delis
Name: categories, dtype: object

In [15]:
review["text"].sample(
    5,
    random_state=42
)

1295256    Went for lunch and found that my burger was me...
3297618    I needed a new tires for my wife's car. They h...
1217795    Jim Woltman who works at Goleta Honda is 5 sta...
3730348    Been here a few times to get some shrimp.  The...
1826590    This is one fantastic place to eat whether you...
Name: text, dtype: object

In [16]:
tip["text"].sample(
    20,
    random_state=42
)

743441                 The Herb Roasted Salmon is great....
867631                                            Auditions
706258       One of my fave spots in Tampa bay! Double yum!
387673      The store here is well organized. I'm impressed
177668    If you want that traditional old diner experie...
214477                                         Seeing Pogo!
636272    Literally, the worst service I've ever receive...
552786    You can ask for more heat if it's not spicy en...
173303    They don't adhere to their hours. Nobody in si...
707777    Super helpful, friendly sales folks! They go t...
58125           Hands down best beer selection in the city!
448269                                      Food & friends!
846035             Hipster vibe. Overpriced, but good food.
358800    This is a Crest, Colgate, Sensodyne toothpaste...
197660                                 Now open on Tuesdays
161601                         Sunny and breezy patio lunch
51351              The eggplant parm is the best slice yet.
725148                       Dirty bathrooms but good food.
149873         Great experience,good prices, awesome fades.
821523                               Cafe aulait! Oooh yaaa
Name: text, dtype: object

In [17]:
tip_counts = tip.groupby(
    "business_id"
).size()

tip_counts.describe()

count    106193.000000
mean          8.559086
std          21.355385
min           1.000000
25%           1.000000
50%           3.000000
75%           8.000000
max        2571.000000
dtype: float64

In [20]:
restaurants.isna().sum().sort_values(ascending=False)

hours           7278
attributes       565
address            0
city               0
business_id        0
name               0
postal_code        0
state              0
latitude           0
longitude          0
review_count       0
stars              0
is_open            0
categories         0
dtype: int64